extends RefCounted

const Program = preload("res://addons/scenario_runtime/program.gd")
const Runtime = preload("res://addons/scenario_runtime/runtime.gd")

func run(h: TestHarness) -> void:
	var program: Dictionary = Program.parse({"kind": "scenario-program-v2", "schema_version": 2, "entry": "start", "cast": [{"actor_id": "guide", "expressions": ["neutral"]}], "endings": [{"outcome_id": "done"}], "blocks": [{"label": "start", "statements": [{"kind": "line", "speaker": "guide", "text": "A voice beyond the stage."}, {"kind": "end", "outcome": "done"}]}]})
	var leaf := HostDialogueLeaf.new()
	leaf.program = program
	leaf._state = Runtime.initial_state(program)
	var snapshot := leaf.snapshot()
	h.assert_eq(snapshot["kind"], "scenario-runtime-snapshot", "the playable leaf saves a content-bound envelope")
	h.assert_eq(Runtime.restore(program, JSON.parse_string(JSON.stringify(snapshot))), leaf.state(), "the leaf save survives JSON")
	var save := CaseSave.of_scenario("synthetic", "opening", PackedStringArray(), leaf.state(), [], "2026-09-13T00:00:00Z", snapshot)
	h.assert_eq(save["scenario"]["program_fingerprint"], snapshot["program_fingerprint"], "the case stores the leaf's exact program identity")
	h.assert_eq(save["statementId"], "start#0", "case resume labels keep their existing identity")
	var changed := program.duplicate(true)
	changed["blocks"][0]["statements"][0]["text"] = "Edited episode."
	h.assert_eq(Runtime.restore(changed, save["scenario"]), null, "updated dialogue refuses an old content-bound save")
	leaf.set_suspended(true)
	leaf.advance()
	h.assert_eq(leaf.state()["index"], 0, "backlog suspension blocks direct leaf advance")
	h.assert_false(h.tree.paused, "leaf suspension never pauses the game's scene tree")
	leaf.set_suspended(false)
	leaf._body = Label.new()
	leaf._name = Label.new()
	leaf._dialogue_portrait = TextureRect.new()
	for child: Control in [leaf._body, leaf._name, leaf._dialogue_portrait]: leaf.add_child(child)
	leaf._body_frame = Rect2(20, 60, 600, 120)
	leaf._name_frame = Rect2(20, 25, 600, 25)
	var image := Image.create(8, 8, false, Image.FORMAT_RGBA8)
	image.fill(Color.WHITE)
	var portrait := ImageTexture.create_from_image(image)
	h.assert_true(leaf.configure_presentation({"portrait": "left"}, {"guide": portrait}).is_empty(), "host can bind a separate dialogue portrait")
	h.assert_true(leaf._dialogue_portrait.visible, "an off-stage speaker can display a dialogue portrait")
	h.assert_true(leaf._body.size.x < 600.0, "present portrait gets a text column")
	h.assert_true(leaf.configure_presentation({"portrait": "left"}).is_empty(), "absent portrait binding is optional")
	h.assert_eq(leaf._body.size.x, 600.0, "absent portrait reflows the text")
	h.assert_false(leaf._dialogue_portrait.visible, "absent optional portrait is hidden")
	h.assert_true(not leaf.configure_presentation({"layout": "bubble"}).is_empty(), "framed game adapter refuses layouts it does not implement")
	leaf.free()
	h.done()
