"""gnode — an asset graph engine.

A build system for generative assets whose contracts must be met: nodes produce
persistent, content-addressed artifacts that are validated before they are
accepted, correctness does not depend on execution order, and failed generation
is retried by exactly one owner.

This module is the public import surface for the engine core and modality
services (rings 0 and 1). Consumers import provider adapters from their declared
``gnode.providers.<name>`` packages (ring 2). Other submodules are internal, so
their layout stays free to move. The engine imports no application package.
"""

from gnode.binding import Binding, BindingTable, CapabilityError, ModelRef
from gnode.contracts import (
    SHA256_PATTERN,
    ArtifactProvenance,
    ArtifactResult,
    ArtifactRights,
    BinaryArtifact,
    ContractModel,
    InputProvenance,
    PersistedContractModel,
    ProvenanceInput,
    RightsStatus,
    SoftwareIdentity,
)
from gnode.modalities._types import ProviderResponseMetadata, validate_optional_timeout
from gnode.modalities.background_removal import BackgroundRemovalRequest, BackgroundRemovalService
from gnode.modalities.image import (
    ImageFacts,
    ImageGenerationRequest,
    ImageGenerationResult,
    ImageGenerationService,
    ImageModelV1,
    ImageReference,
    ImageRouteRequirementsV1,
    PromptAnchor,
    ProviderImage,
    apply_resolved_image_binding,
    classify_image_reference_delivery,
    inspect_image,
)
from gnode.modalities.image.models import ImageQuality, ImageResolution
from gnode.modalities.music import MusicGenerationRequest, MusicGenerationService
from gnode.modalities.signatures import (
    assert_audio_signature,
    assert_image_signature,
    normalize_audio_media_type,
    normalize_media_type,
)
from gnode.modalities.sound_effect import (
    ProviderSoundEffect,
    SoundEffectGenerationRequest,
    SoundEffectGenerationService,
)
from gnode.modalities.speech import (
    ProviderSpeech,
    SpeechGenerationRequest,
    SpeechGenerationService,
)
from gnode.modalities.structured import (
    ProviderStructuredOutput,
    StructuredGenerationRequest,
    StructuredGenerationResult,
    StructuredGenerationService,
    StructuredOutputSchema,
    StructuredReference,
    canonicalize_strict_json_schema,
)
from gnode.modalities.tool_loop import (
    ProviderToolLoopStep,
    Tool,
    ToolCall,
    ToolInvocationError,
    ToolLoopExhausted,
    ToolLoopMessage,
    ToolLoopReference,
    ToolLoopRequest,
    ToolLoopService,
    ToolLoopStepRequest,
    ToolResult,
    ToolSpec,
)
from gnode.modalities.video import (
    ProviderVideo,
    VideoGenerationRequest,
    VideoGenerationService,
    VideoReference,
    VideoResolution,
)
from gnode.node_types import NodePolicy, NodeType, ViewArchetype
from gnode.records import LOCAL_OPERATION, ResolvedRouteSnapshotV1
from gnode.reliability import (
    AbortError,
    ArtifactBundleEntry,
    AtomicBundleFile,
    AtomicWriteError,
    CancellationError,
    CancellationToken,
    LocalFileOperations,
    NonRetryableError,
    RetryContext,
    RetryExhaustedError,
    RetryPolicy,
    assert_media_type,
    assert_safe_path_segment,
    atomic_write_bundle,
    atomic_write_bytes,
    atomic_write_json,
    atomic_write_text,
    build_artifact_provenance,
    decode_base64_strict,
    hash_input_reference,
    is_portable_artifact_reference,
    is_temporary_artifact_reference,
    record_artifact_rights,
    redact_secrets,
    resolve_relative_path_within_root,
    resolve_writable_path_within_root,
    retry_with_backoff,
    sanitize_for_persistence,
    sanitize_reference,
    serialize_provenance,
    sha256_hex,
    write_artifact_bundle_with_provenance,
    write_artifact_with_provenance,
    write_artifact_with_provenance_async,
)
from gnode.route_constraints import ExactSize2DV1, ExactSizeConstraints2DV1
from gnode.routes import (
    ResolvedBindingV1,
    RouteCatalog,
    RouteCatalogError,
    RouteContractV1,
    RouteResolutionError,
    WorkloadPolicyV1,
    WorkloadRequestV1,
)
from gnode.trace import RUN_EVENTS_SCHEMA_VERSION
from gnode.view import RUN_VIEW_SCHEMA_VERSION, RunView, RunViewArtifact, artifact_media_type
from gnode.workflow import cli
from gnode.workflow.api import RunResult, plan, plan_async, run, run_async
from gnode.workflow.builder import Group, StepRef, Workflow
from gnode.workflow.dashboard import Dashboard, view_key
from gnode.workflow.describe import StepDescription, WorkflowDescription, describe
from gnode.workflow.host import (
    CallRefused,
    CapabilityHandler,
    Ctx,
    HostServices,
    JobLog,
    LongJob,
    NodeFailure,
    ToolReply,
    register_reader,
    register_writer,
    resolve_tool,
    tool,
)
from gnode.workflow.plan import Plan, PlanError, Planner, Project, make_plan, make_planner
from gnode.workflow.plugins import Plugin
from gnode.workflow.registry import BuiltinType
from gnode.workflow.routes import Route, RoutePrice, RouteTable
from gnode.workflow.run import RunOutcome, RunRefused, WorkflowRun
from gnode.workflow.runview import (
    is_workflow_run,
    project_run,
    read_plan,
    verify_run,
    view_contexts,
)
from gnode.workflow.schemas import all_schemas as document_schemas
from gnode.workflow.spec import NodeSpec, PortSpec, node, param_schema
from gnode.workflow.store import CallRecord, Store
from gnode.workflow.values import FileValue

__all__ = [
    "RUN_VIEW_SCHEMA_VERSION",
    "LOCAL_OPERATION",
    "RUN_EVENTS_SCHEMA_VERSION",
    "SHA256_PATTERN",
    "AbortError",
    "ArtifactBundleEntry",
    "ArtifactProvenance",
    "ArtifactResult",
    "ArtifactRights",
    "AtomicBundleFile",
    "AtomicWriteError",
    "BackgroundRemovalRequest",
    "BackgroundRemovalService",
    "BinaryArtifact",
    "Binding",
    "BindingTable",
    "BuiltinType",
    "CallRecord",
    "CallRefused",
    "CancellationError",
    "CancellationToken",
    "CapabilityError",
    "CapabilityHandler",
    "ContractModel",
    "Ctx",
    "Dashboard",
    "ExactSize2DV1",
    "ExactSizeConstraints2DV1",
    "FileValue",
    "Group",
    "HostServices",
    "ImageFacts",
    "ImageGenerationRequest",
    "ImageGenerationResult",
    "ImageGenerationService",
    "ImageModelV1",
    "ImageQuality",
    "ImageReference",
    "ImageResolution",
    "ImageRouteRequirementsV1",
    "InputProvenance",
    "JobLog",
    "LocalFileOperations",
    "LongJob",
    "ModelRef",
    "MusicGenerationRequest",
    "MusicGenerationService",
    "NodeFailure",
    "NodePolicy",
    "NodeSpec",
    "NodeType",
    "NonRetryableError",
    "PersistedContractModel",
    "Plan",
    "PlanError",
    "Planner",
    "Plugin",
    "PortSpec",
    "Project",
    "PromptAnchor",
    "ProvenanceInput",
    "ProviderImage",
    "ProviderResponseMetadata",
    "ProviderSoundEffect",
    "ProviderSpeech",
    "ProviderStructuredOutput",
    "ProviderToolLoopStep",
    "ProviderVideo",
    "ResolvedBindingV1",
    "ResolvedRouteSnapshotV1",
    "RetryContext",
    "RetryExhaustedError",
    "RetryPolicy",
    "RightsStatus",
    "Route",
    "RouteCatalog",
    "RouteCatalogError",
    "RouteContractV1",
    "RoutePrice",
    "RouteResolutionError",
    "RouteTable",
    "RunOutcome",
    "RunRefused",
    "RunResult",
    "RunView",
    "RunViewArtifact",
    "SoftwareIdentity",
    "SoundEffectGenerationRequest",
    "SoundEffectGenerationService",
    "SpeechGenerationRequest",
    "SpeechGenerationService",
    "StepDescription",
    "StepRef",
    "Store",
    "StructuredGenerationRequest",
    "StructuredGenerationResult",
    "StructuredGenerationService",
    "StructuredOutputSchema",
    "StructuredReference",
    "Tool",
    "ToolCall",
    "ToolInvocationError",
    "ToolLoopExhausted",
    "ToolLoopMessage",
    "ToolLoopReference",
    "ToolLoopRequest",
    "ToolLoopService",
    "ToolLoopStepRequest",
    "ToolReply",
    "ToolResult",
    "ToolSpec",
    "VideoGenerationRequest",
    "VideoGenerationService",
    "VideoReference",
    "VideoResolution",
    "ViewArchetype",
    "Workflow",
    "WorkflowDescription",
    "WorkflowRun",
    "WorkloadPolicyV1",
    "WorkloadRequestV1",
    "apply_resolved_image_binding",
    "artifact_media_type",
    "assert_audio_signature",
    "assert_image_signature",
    "assert_media_type",
    "assert_safe_path_segment",
    "atomic_write_bundle",
    "atomic_write_bytes",
    "atomic_write_json",
    "atomic_write_text",
    "build_artifact_provenance",
    "canonicalize_strict_json_schema",
    "classify_image_reference_delivery",
    "cli",
    "decode_base64_strict",
    "describe",
    "document_schemas",
    "hash_input_reference",
    "inspect_image",
    "is_portable_artifact_reference",
    "is_temporary_artifact_reference",
    "is_workflow_run",
    "make_plan",
    "make_planner",
    "node",
    "normalize_audio_media_type",
    "normalize_media_type",
    "param_schema",
    "plan",
    "plan_async",
    "project_run",
    "read_plan",
    "record_artifact_rights",
    "redact_secrets",
    "register_reader",
    "register_writer",
    "resolve_relative_path_within_root",
    "resolve_tool",
    "resolve_writable_path_within_root",
    "retry_with_backoff",
    "run",
    "run_async",
    "sanitize_for_persistence",
    "sanitize_reference",
    "serialize_provenance",
    "sha256_hex",
    "tool",
    "validate_optional_timeout",
    "verify_run",
    "view_contexts",
    "view_key",
    "write_artifact_bundle_with_provenance",
    "write_artifact_with_provenance",
    "write_artifact_with_provenance_async",
]
