"""World generation as point processes over fields, with no vocabulary of its own.

WHAT THIS IS. Fields over a square world (regions solved to authored shares,
a coast, a rules-only height, distances to water, to a region's edge, to a
road, to a set piece), four point processes (Poisson, Matérn cluster,
attached to another object's points, spaced on a jittered grid) drawn from
salted, addressable draws so an edit to one object moves only that object,
two hard cores (an object's own spacing; every object's footprint, which only
ever deletes), quotas, set pieces sited whole, and a measurement of whether a
pattern came out as authored, against a Monte-Carlo null on the same fields.

WHAT THIS IS NOT. It has no vocabulary: regions are integers, objects are id
strings, and a caller binds its own words to them. It renders nothing but
data plates. It schedules no work and calls no provider.
"""

from .fields import (
    ANALYSIS_CELLS,
    REGION_LATTICE,
    Bump,
    Clearing,
    Coast,
    GridSpec,
    IndexGrid,
    RegionField,
    ScalarGrid,
    ValueNoise,
    WorldFields,
    band,
    chamfer_distance,
    patch_chord_meters,
    smoothstep,
    solve_threshold,
    trapezoid,
)
from .hashing import M64, SALT_SEP, Stream, fnv1a64, splitmix64
from .measure import (
    CLUSTER_K_MIN,
    CLUSTER_R_MAX,
    MEASURE_MIN_PAIRS,
    MEASURE_MIN_POINTS,
    NULL_REPLICATES,
    SPACED_R_MIN,
    PatternReport,
    mean_nearest_neighbour,
    measure_object,
    neighbours_within,
    refuse_patterns,
)
from .processes import (
    LAMBDA_CELL_MAX,
    LAMBDA_CELL_TARGET,
    Candidate,
    HostPoint,
    attached_candidates,
    candidates_for,
    cell_meters_for,
    check_spec,
    cluster_candidates,
    packing_limit_per_100m2,
    poisson_candidates,
    poisson_count,
    spaced_candidates,
)
from .raster import (
    PLATE_CELL_METERS,
    PLATE_CELLS_MAX,
    Plate,
    plate_cells,
    polyline_distance,
    segment_distance,
)
from .sampler import (
    ObjectTally,
    Placed,
    PointIndex,
    WorldPlan,
    accept_own,
    apply_quota,
    drop_neighbours,
    plan_world,
)
from .setpieces import MAX_SITE_TRIES, MemberPoint, SetPieceSite, place_set_pieces
from .spec import (
    DEFAULT_MARKS,
    AttachedProcess,
    AvoidRule,
    ClusterProcess,
    EdgeSpec,
    HabitatSpec,
    HeightBand,
    ObjectSpec,
    PoissonProcess,
    Process,
    Quota,
    SetPieceMember,
    SetPieceSpec,
    SpacedProcess,
    SpecError,
    WorldSpec,
    placement_order,
)

__all__ = [
    "ANALYSIS_CELLS",
    "CLUSTER_K_MIN",
    "CLUSTER_R_MAX",
    "DEFAULT_MARKS",
    "LAMBDA_CELL_MAX",
    "LAMBDA_CELL_TARGET",
    "M64",
    "MAX_SITE_TRIES",
    "MEASURE_MIN_PAIRS",
    "MEASURE_MIN_POINTS",
    "NULL_REPLICATES",
    "PLATE_CELLS_MAX",
    "PLATE_CELL_METERS",
    "REGION_LATTICE",
    "SALT_SEP",
    "SPACED_R_MIN",
    "AttachedProcess",
    "AvoidRule",
    "Bump",
    "Candidate",
    "Clearing",
    "ClusterProcess",
    "Coast",
    "EdgeSpec",
    "GridSpec",
    "HabitatSpec",
    "HeightBand",
    "HostPoint",
    "IndexGrid",
    "MemberPoint",
    "ObjectSpec",
    "ObjectTally",
    "PatternReport",
    "Placed",
    "Plate",
    "PointIndex",
    "PoissonProcess",
    "Process",
    "Quota",
    "RegionField",
    "ScalarGrid",
    "SetPieceMember",
    "SetPieceSite",
    "SetPieceSpec",
    "SpacedProcess",
    "SpecError",
    "Stream",
    "ValueNoise",
    "WorldFields",
    "WorldPlan",
    "WorldSpec",
    "accept_own",
    "apply_quota",
    "attached_candidates",
    "band",
    "candidates_for",
    "cell_meters_for",
    "chamfer_distance",
    "check_spec",
    "cluster_candidates",
    "drop_neighbours",
    "fnv1a64",
    "mean_nearest_neighbour",
    "measure_object",
    "neighbours_within",
    "packing_limit_per_100m2",
    "patch_chord_meters",
    "place_set_pieces",
    "placement_order",
    "plan_world",
    "plate_cells",
    "poisson_candidates",
    "poisson_count",
    "polyline_distance",
    "refuse_patterns",
    "segment_distance",
    "smoothstep",
    "solve_threshold",
    "spaced_candidates",
    "splitmix64",
    "trapezoid",
]
