"""Deterministic media inspection and post-processing helpers."""

from .audio import (
    DEFAULT_AUDIO_PROCESS_TIMEOUT_SECONDS,
    AudioProbe,
    AudioProcessResult,
    AudioProcessRunner,
    LoudnessMeasurement,
    assert_audio_signature,
    normalize_audio_media_type,
    parse_loudnorm_json,
    probe_audio,
    run_process,
)
from .images import (
    CHROMA_DISTANCE_THRESHOLD,
    CHROMA_MATTE_VERSION,
    MAGENTA_EDGE_DECONTAMINATION_VERSION,
    AlphaFacts,
    ImageFacts,
    ImageNormalizationRecord,
    MagentaEdgeDecontaminationFacts,
    apply_chroma_transparency,
    compose_source_with_alpha,
    decontaminate_magenta_edges,
    inspect_image,
    normalize_png,
)
from .validation import (
    assert_image_signature,
    decode_base64_strict,
    normalize_media_type,
)

__all__ = [
    "CHROMA_DISTANCE_THRESHOLD",
    "DEFAULT_AUDIO_PROCESS_TIMEOUT_SECONDS",
    "AlphaFacts",
    "AudioProbe",
    "AudioProcessResult",
    "AudioProcessRunner",
    "ImageFacts",
    "ImageNormalizationRecord",
    "LoudnessMeasurement",
    "CHROMA_MATTE_VERSION",
    "MAGENTA_EDGE_DECONTAMINATION_VERSION",
    "MagentaEdgeDecontaminationFacts",
    "apply_chroma_transparency",
    "assert_audio_signature",
    "assert_image_signature",
    "compose_source_with_alpha",
    "decontaminate_magenta_edges",
    "decode_base64_strict",
    "inspect_image",
    "normalize_audio_media_type",
    "normalize_media_type",
    "normalize_png",
    "parse_loudnorm_json",
    "probe_audio",
    "run_process",
]
