"""Deterministic media inspection and post-processing helpers."""

from .audio import (
    DEFAULT_AUDIO_PROCESS_TIMEOUT_SECONDS,
    AudioProbe,
    AudioProcessResult,
    AudioProcessRunner,
    LoudnessMeasurement,
    assert_audio_signature,
    normalize_audio_media_type,
    parse_loudnorm_json,
    probe_audio,
    run_process,
)
from .guide_lattice import (
    CYAN_GUIDES,
    GuideColorContract,
    GuideLattice,
    detect_guide_lattice,
    extract_guided_cells,
    magenta_chroma_alpha,
    repair_internal_cell_seams,
)
from .images import (
    CHROMA_DISTANCE_THRESHOLD,
    CHROMA_MATTE_VERSION,
    MAGENTA_EDGE_DECONTAMINATION_VERSION,
    NATIVE_ALPHA_OPAQUE_THRESHOLD,
    AlphaFacts,
    ImageFacts,
    ImageNormalizationRecord,
    MagentaEdgeDecontaminationFacts,
    apply_chroma_transparency,
    compose_source_with_alpha,
    decontaminate_magenta_edges,
    inspect_image,
    normalize_image_to_png,
    normalize_png,
    normalize_png_cover,
)
from .sprite_sheets import (
    ALPHA_COMPONENT_REPACK_VERSION,
    ALPHA_GROUND_CONTACT_VERSION,
    AlphaComponentRepackContract,
    measure_alpha_ground_contact,
    repack_alpha_components,
)
from .validation import (
    assert_image_signature,
    decode_base64_strict,
    normalize_media_type,
)

__all__ = [
    "CHROMA_DISTANCE_THRESHOLD",
    "DEFAULT_AUDIO_PROCESS_TIMEOUT_SECONDS",
    "AlphaFacts",
    "AlphaComponentRepackContract",
    "AudioProbe",
    "AudioProcessResult",
    "AudioProcessRunner",
    "ImageFacts",
    "ImageNormalizationRecord",
    "LoudnessMeasurement",
    "CHROMA_MATTE_VERSION",
    "CYAN_GUIDES",
    "GuideColorContract",
    "GuideLattice",
    "MAGENTA_EDGE_DECONTAMINATION_VERSION",
    "NATIVE_ALPHA_OPAQUE_THRESHOLD",
    "ALPHA_COMPONENT_REPACK_VERSION",
    "ALPHA_GROUND_CONTACT_VERSION",
    "MagentaEdgeDecontaminationFacts",
    "apply_chroma_transparency",
    "assert_audio_signature",
    "assert_image_signature",
    "compose_source_with_alpha",
    "decontaminate_magenta_edges",
    "detect_guide_lattice",
    "decode_base64_strict",
    "inspect_image",
    "extract_guided_cells",
    "magenta_chroma_alpha",
    "measure_alpha_ground_contact",
    "normalize_audio_media_type",
    "normalize_media_type",
    "normalize_image_to_png",
    "normalize_png",
    "normalize_png_cover",
    "parse_loudnorm_json",
    "probe_audio",
    "repack_alpha_components",
    "repair_internal_cell_seams",
    "run_process",
]
