"""The game shell: the opening cinematic, the title screen and the loading screen.

One recipe-neutral component, consumed by every genre that has a host to show them in.
The composition of these screens is genre-neutral — a backdrop, a mark, a control stack,
a shot list — while their content is authored per package, which is the same split
``game_ui`` already makes and the reason this is a component rather than a recipe.

See ``docs/spec/game/shell.md``.
"""

from stage_gen.components.game_shell.layouts import (
    BACKDROP_DEPTHS,
    CUTOUT_ALPHA_POLICY,
    LOADING_SCREEN,
    LOADING_SCREEN_LAYOUT,
    OPAQUE_ALPHA_POLICY,
    OPENING_LAYOUT,
    OPENING_SHOT,
    SHELL_CANVAS,
    SHELL_LAYOUTS,
    SHOT_MOVES,
    SHOT_TRANSITIONS,
    TITLE_SCREEN,
    TITLE_SCREEN_LAYOUT,
    Rect,
    ShellLayout,
)
from stage_gen.components.game_shell.models import (
    FIRST_SHELL_TAKE,
    FONT_SUFFIXES,
    GAME_SHELL_KIND,
    GAME_SHELL_SCHEMA_VERSION,
    MAX_SHELL_TAKE,
    REDISTRIBUTABLE_FONT_LICENSES,
    BackdropLayer,
    GameShell,
    LoadingBackdropBinding,
    LoadingScreen,
    Opening,
    OpeningShot,
    ShellClip,
    ShellPlate,
    ShellReference,
    ShellTypeface,
    ShotPlate,
    TitleScreen,
    load_game_shell_bytes,
)

__all__ = [
    "BACKDROP_DEPTHS",
    "BackdropLayer",
    "CUTOUT_ALPHA_POLICY",
    "FIRST_SHELL_TAKE",
    "FONT_SUFFIXES",
    "GAME_SHELL_KIND",
    "GAME_SHELL_SCHEMA_VERSION",
    "GameShell",
    "load_game_shell_bytes",
    "LOADING_SCREEN",
    "LOADING_SCREEN_LAYOUT",
    "LoadingBackdropBinding",
    "LoadingScreen",
    "MAX_SHELL_TAKE",
    "OPAQUE_ALPHA_POLICY",
    "Opening",
    "OPENING_LAYOUT",
    "OPENING_SHOT",
    "OpeningShot",
    "Rect",
    "REDISTRIBUTABLE_FONT_LICENSES",
    "SHELL_CANVAS",
    "SHELL_LAYOUTS",
    "ShellClip",
    "ShellLayout",
    "ShellPlate",
    "ShellReference",
    "ShellTypeface",
    "SHOT_MOVES",
    "SHOT_TRANSITIONS",
    "ShotPlate",
    "TITLE_SCREEN",
    "TITLE_SCREEN_LAYOUT",
    "TitleScreen",
]
