"""The horizontal-loop parallax layer discipline shared by side-view genres."""

from .contract import (
    BOTTOM_REGISTERED_ANCHORS,
    LAYER_PLACEMENT_CANONICALIZER,
    LOOP_ANCHOR_BAND_PX,
    LOOP_BRIDGE_BRIEF_FRAMING,
    LOOP_BRIDGE_BRIEF_VERSION,
    LOOP_BRIDGE_CONTEXT_SPAN_PX,
    LOOP_BRIDGE_SPAN_PX,
    LOOP_REPAINT_BRIEF_FRAMING,
    LOOP_REPAINT_BRIEF_VERSION,
    LOOP_REPAINT_SPAN_PX,
    LOOP_REPAINT_WINDOW_PX,
    NON_GENERATIVE_LAYER_FIELDS,
    PLACEMENT_ONLY_CLIMBABLE_FIELDS,
    PLACEMENT_ONLY_GROUND_FIELDS,
    RUNTIME_ONLY_LAYER_FIELDS,
    TOP_REGISTERED_ANCHORS,
    PlacedLayer,
    loop_method_identity,
    resolve_layer_placement,
)
from .pipeline import (
    PROVIDER_VISIBLE_ALPHA_MIN,
    LoopOutcome,
    assemble_loop,
    construct_deterministic,
    layer_repeat_policies,
    loop_conditioning,
    loop_layer,
    validate_provider_image,
)

__all__ = [
    "BOTTOM_REGISTERED_ANCHORS",
    "LAYER_PLACEMENT_CANONICALIZER",
    "LOOP_ANCHOR_BAND_PX",
    "LOOP_BRIDGE_BRIEF_FRAMING",
    "LOOP_BRIDGE_BRIEF_VERSION",
    "LOOP_BRIDGE_CONTEXT_SPAN_PX",
    "LOOP_BRIDGE_SPAN_PX",
    "LOOP_REPAINT_BRIEF_FRAMING",
    "LOOP_REPAINT_BRIEF_VERSION",
    "LOOP_REPAINT_SPAN_PX",
    "LOOP_REPAINT_WINDOW_PX",
    "NON_GENERATIVE_LAYER_FIELDS",
    "PLACEMENT_ONLY_CLIMBABLE_FIELDS",
    "PLACEMENT_ONLY_GROUND_FIELDS",
    "PROVIDER_VISIBLE_ALPHA_MIN",
    "RUNTIME_ONLY_LAYER_FIELDS",
    "TOP_REGISTERED_ANCHORS",
    "LoopOutcome",
    "PlacedLayer",
    "assemble_loop",
    "construct_deterministic",
    "layer_repeat_policies",
    "loop_conditioning",
    "loop_layer",
    "loop_method_identity",
    "resolve_layer_placement",
    "validate_provider_image",
]
