"""Actor magnitude and motion admission shared by side-view genres.

A side-view actor's drawn magnitude and its scale-rebase admission are
camera-scoped facts: a runner avatar and a platformer player are measured,
calibrated, and judged the same way. Per-genre motion-state vocabulary and
rank ladders stay with their genre.
"""

from .asset_unit import (
    ASSET_UNIT_ERROR_CODE,
    DOWNSCALE_WARN_RATIO,
    ENTITY_CONSISTENCY_FACTOR,
    PAINTED_ALPHA_THRESHOLD,
    PLAYER_HEIGHT_UNITS,
    AssetUnitError,
    ResolvedMagnitude,
    SubjectCalibration,
    admit_entity_consistency,
    calibrate_subject,
    measure_subject_extent,
    recovery_plate_steps,
    resolve_declared_magnitude,
    resolve_player_magnitude,
    sprite_scale,
)
from .motion_rebase import (
    BASELINE_STATE,
    MOTION_REBASE_CORRECTION_SCHEMA_NAME,
    MOTION_REBASE_ERROR_CODE,
    MOTION_REBASE_SCHEMA_NAME,
    MotionRebaseError,
    MotionRebaseReading,
    StateRebaseReading,
    admit_first_pass_record,
    build_motion_rebase_plate,
    build_motion_rebase_verification_plate,
    evaluate_motion_rebase,
    evaluate_motion_rebase_correction,
    motion_rebase_json_schema,
    motion_rebase_prompt,
    motion_rebase_verification_prompt,
    parse_motion_rebase,
)
from .motion_rebase_nodes import (
    MOTION_REBASE_JUDGE,
    MOTION_REBASE_VERIFY,
    REBASE_PLATE_KIND,
    REBASE_READING_KIND,
    REBASE_VERIFICATION_KIND,
    MotionRebaseHandlers,
    MotionRebaseHost,
    MotionRebaseNodeTypes,
    RebaseLayout,
    RebaseSubject,
    add_motion_rebase_nodes,
    motion_rebase_node_types,
)

__all__ = [
    "ASSET_UNIT_ERROR_CODE",
    "BASELINE_STATE",
    "DOWNSCALE_WARN_RATIO",
    "ENTITY_CONSISTENCY_FACTOR",
    "MOTION_REBASE_CORRECTION_SCHEMA_NAME",
    "MOTION_REBASE_ERROR_CODE",
    "MOTION_REBASE_JUDGE",
    "MOTION_REBASE_SCHEMA_NAME",
    "MOTION_REBASE_VERIFY",
    "PAINTED_ALPHA_THRESHOLD",
    "PLAYER_HEIGHT_UNITS",
    "REBASE_PLATE_KIND",
    "REBASE_READING_KIND",
    "REBASE_VERIFICATION_KIND",
    "AssetUnitError",
    "MotionRebaseError",
    "MotionRebaseHandlers",
    "MotionRebaseHost",
    "MotionRebaseNodeTypes",
    "MotionRebaseReading",
    "RebaseLayout",
    "RebaseSubject",
    "ResolvedMagnitude",
    "StateRebaseReading",
    "SubjectCalibration",
    "add_motion_rebase_nodes",
    "admit_entity_consistency",
    "admit_first_pass_record",
    "build_motion_rebase_plate",
    "build_motion_rebase_verification_plate",
    "calibrate_subject",
    "evaluate_motion_rebase",
    "evaluate_motion_rebase_correction",
    "measure_subject_extent",
    "motion_rebase_json_schema",
    "motion_rebase_node_types",
    "motion_rebase_prompt",
    "motion_rebase_verification_prompt",
    "parse_motion_rebase",
    "recovery_plate_steps",
    "resolve_declared_magnitude",
    "resolve_player_magnitude",
    "sprite_scale",
]
