"""The `scenario-v2` authored narrative contract: parse, compile, prove, resolve.

Recipe-neutral on purpose. A scenario carries no genre, no engine, and no
generation vocabulary, because the visual novel and the platformer's village
dialogue are meant to consume the same authored shape rather than each keeping a
parallel one that can drift. See `docs/spec/game/scenario.md`.
"""

from .admission import (
    MAX_IMPORTED_FLAGS,
    MAX_REACHABLE_STATES,
    ScenarioAdmissionError,
    ScenarioState,
    admit_scenario,
)
from .compile import ScenarioCompileError, compile_scenario
from .models import (
    RESERVED_WORDS,
    SCENARIO_CATALOG_KIND,
    SCENARIO_CATALOG_NAME,
    SCENARIO_CATALOG_SCHEMA_VERSION,
    SCENARIO_KIND,
    SCENARIO_SCHEMA_VERSION,
    SLOTS,
    TERMINAL_KINDS,
    AudioStatement,
    Block,
    BranchEdge,
    BranchStatement,
    CastMember,
    ChoiceOption,
    ChoiceStatement,
    Condition,
    EndingDeclaration,
    EndingWitness,
    EndStatement,
    FlagDeclaration,
    HideStatement,
    JumpStatement,
    LineStatement,
    ScenarioAdmissionReport,
    ScenarioCatalog,
    ScenarioDeclarations,
    ScenarioProgram,
    ScenarioSource,
    SetStatement,
    ShowStatement,
    Slot,
    StageDeclaration,
    StageStatement,
    Statement,
    TrackDeclaration,
)
from .parser import RawBlock, RawIf, ScenarioSyntaxError, parse_scenario
from .resolve import (
    SCENARIO_RESOLUTION_VERSION,
    ResolvedScenario,
    canonical_program_json,
    load_scenario_catalog_bytes,
    read_scenario_catalog,
    read_scenario_declarations,
    read_script_text,
    resolve_scenario,
    resolve_scenario_bytes,
    resolve_scenario_catalog,
    script_digest,
)

__all__ = [
    "MAX_IMPORTED_FLAGS",
    "MAX_REACHABLE_STATES",
    "RESERVED_WORDS",
    "SCENARIO_CATALOG_KIND",
    "SCENARIO_CATALOG_NAME",
    "SCENARIO_CATALOG_SCHEMA_VERSION",
    "SCENARIO_KIND",
    "SCENARIO_RESOLUTION_VERSION",
    "SCENARIO_SCHEMA_VERSION",
    "SLOTS",
    "TERMINAL_KINDS",
    "AudioStatement",
    "Block",
    "BranchEdge",
    "BranchStatement",
    "CastMember",
    "ChoiceOption",
    "ChoiceStatement",
    "Condition",
    "EndStatement",
    "EndingDeclaration",
    "EndingWitness",
    "FlagDeclaration",
    "HideStatement",
    "JumpStatement",
    "LineStatement",
    "RawBlock",
    "RawIf",
    "ResolvedScenario",
    "ScenarioAdmissionError",
    "ScenarioAdmissionReport",
    "ScenarioCompileError",
    "ScenarioCatalog",
    "ScenarioDeclarations",
    "ScenarioSource",
    "ScenarioProgram",
    "ScenarioState",
    "ScenarioSyntaxError",
    "SetStatement",
    "ShowStatement",
    "Slot",
    "StageDeclaration",
    "StageStatement",
    "Statement",
    "TrackDeclaration",
    "admit_scenario",
    "canonical_program_json",
    "compile_scenario",
    "parse_scenario",
    "read_scenario_declarations",
    "read_script_text",
    "load_scenario_catalog_bytes",
    "read_scenario_catalog",
    "resolve_scenario",
    "resolve_scenario_bytes",
    "resolve_scenario_catalog",
    "script_digest",
]
