"""Actor magnitude and motion admission shared by side-view genres.

A side-view actor's drawn magnitude and its scale-rebase admission are
camera-scoped facts: a runner avatar and a platformer player are measured,
calibrated, and judged the same way. Per-genre motion-state vocabulary and
rank ladders stay with their genre.
"""

from .asset_unit import (
    ASSET_UNIT_ERROR_CODE,
    DOWNSCALE_WARN_RATIO,
    ENTITY_CONSISTENCY_FACTOR,
    PAINTED_ALPHA_THRESHOLD,
    AssetScale,
    AssetUnitError,
    ResolvedMagnitude,
    SubjectCalibration,
    admit_entity_consistency,
    calibrate_subject,
    measure_subject_extent,
    recovery_plate_steps,
    resolve_declared_magnitude,
    sprite_scale,
)
from .motion_rebase import (
    BASELINE_STATE,
    MOTION_REBASE_CORRECTION_SCHEMA_NAME,
    MOTION_REBASE_ERROR_CODE,
    MOTION_REBASE_SCHEMA_NAME,
    MotionRebaseError,
    MotionRebaseReading,
    StateRebaseReading,
    admit_first_pass_record,
    build_motion_rebase_plate,
    build_motion_rebase_verification_plate,
    evaluate_motion_rebase,
    evaluate_motion_rebase_correction,
    motion_rebase_json_schema,
    motion_rebase_prompt,
    motion_rebase_verification_prompt,
    parse_motion_rebase,
)

__all__ = [
    "ASSET_UNIT_ERROR_CODE",
    "BASELINE_STATE",
    "DOWNSCALE_WARN_RATIO",
    "ENTITY_CONSISTENCY_FACTOR",
    "MOTION_REBASE_CORRECTION_SCHEMA_NAME",
    "MOTION_REBASE_ERROR_CODE",
    "MOTION_REBASE_SCHEMA_NAME",
    "PAINTED_ALPHA_THRESHOLD",
    "AssetScale",
    "AssetUnitError",
    "MotionRebaseError",
    "MotionRebaseReading",
    "ResolvedMagnitude",
    "StateRebaseReading",
    "SubjectCalibration",
    "admit_entity_consistency",
    "admit_first_pass_record",
    "build_motion_rebase_plate",
    "build_motion_rebase_verification_plate",
    "calibrate_subject",
    "evaluate_motion_rebase",
    "evaluate_motion_rebase_correction",
    "measure_subject_extent",
    "motion_rebase_json_schema",
    "motion_rebase_prompt",
    "motion_rebase_verification_prompt",
    "parse_motion_rebase",
    "recovery_plate_steps",
    "resolve_declared_magnitude",
    "sprite_scale",
]
