#!/usr/bin/env python3
"""Compose and inspect a map's terrain offline.

Terrain is generated by the pipeline, the way artwork is: the map document states a generator
and a brief, and the graph produces a ``map-terrain-v1`` artifact. This script is the offline
bench for that path. It does not edit a map document and it never writes geometry back into one,
because a map that carried its own compiled terrain is exactly what this contract removed.

The capability profile is not defined here either. It is derived from the authored map by
``terrain_profile``, so the rules a design is judged against are the ones the map actually
declares rather than a copy that can drift.

    uv run python scripts/design_map.py check --map crowncrag-road --design design.json
    uv run python scripts/design_map.py render --map crowncrag-road --example --out /tmp/road.png
    uv run python scripts/design_map.py compile --map crowncrag-road --example --run-dir out/<run>
    STAGE_GEN_RUN_LIVE=1 uv run python scripts/design_map.py design \
        --map crowncrag-road --live --out design.json
"""

from __future__ import annotations

import argparse
import asyncio
import os
import sys
from collections.abc import Sequence
from pathlib import Path

if __package__ in {None, ""}:
    sys.path.insert(0, str(Path(__file__).resolve().parents[1] / "src"))
    sys.path.insert(0, str(Path(__file__).resolve().parents[1]))

from stage_gen.components.game_map import PreparedGameMap, load_prepared_game_map_bytes
from stage_gen.components.game_map.prepared import (
    canonical_prepared_map_terrain_json,
    validate_generated_terrain,
)
from stage_gen.components.platformer_map_design import (
    DesignBrief,
    DesignedMap,
    PlatformerChunkMapDesign,
    PlatformerProfile,
    check,
    design_chunks,
    expand_chunks,
    load_platformer_chunk_map_design_bytes,
    translate,
    vocabulary,
)
from stage_gen.recipes.scrolling_preview.terrain_design import (
    compile_terrain,
    terrain_artifact_path,
    terrain_profile,
)

REPOSITORY_ROOT = Path(__file__).resolve().parents[1]
DEFAULT_LIBRARY_ROOT = REPOSITORY_ROOT / "library" / "games"

#: A sentence that satisfies the shipped road's own rules, so every offline subcommand can be
#: exercised with no external file.
EXAMPLE_CHUNKS: list[dict[str, object]] = [
    {"kind": "run", "len": 6},
    {"kind": "perch", "platform_width": 6, "climb_rise": 4, "variant": "bellroot_ladder"},
    {"kind": "slope", "rise": 2, "grade": "gentle", "dir": "up"},
    {"kind": "run", "len": 4},
    {"kind": "perch", "platform_width": 6, "climb_rise": 4, "variant": "shrine_rope_ladder"},
    {"kind": "hollow", "width": 6, "depth": 2},
    {"kind": "slope", "rise": 2, "grade": "gentle", "dir": "down"},
    {"kind": "run", "len": 4},
    {"kind": "hop_chain", "count": 3, "jump_rise": 1, "gap": 3, "platform_width": 4, "dir": "up"},
    {"kind": "run", "len": 4},
    {"kind": "perch", "platform_width": 6, "climb_rise": 4, "variant": "bellrope_climb"},
    {"kind": "slope", "rise": 2, "grade": "gentle", "dir": "up"},
    {"kind": "run", "len": 4},
    {"kind": "perch", "platform_width": 6, "climb_rise": 4, "variant": "bellroot_ladder"},
]


class MapDesignError(ValueError):
    """A design that the map it targets will not accept."""


def load_map(library_root: Path, map_id: str) -> PreparedGameMap:
    path = library_root / "bellweather" / "maps" / f"{map_id}.toml"
    if not path.is_file():
        raise MapDesignError(f"no authored map document at {path}")
    return load_prepared_game_map_bytes(path.read_bytes())


def example_design(game_map: PreparedGameMap) -> PlatformerChunkMapDesign:
    return PlatformerChunkMapDesign(
        schema_version=1,
        kind="platformer-chunk-map-v1",
        profile_id=terrain_profile(game_map).profile_id,
        columns=game_map.terrain.columns,
        start_height_tiles=3,
        design_notes="The offline example sentence.",
        chunks=EXAMPLE_CHUNKS,
        brief=game_map.terrain.brief,
    )


def resolve_design(
    game_map: PreparedGameMap, design_path: Path | None, use_example: bool
) -> PlatformerChunkMapDesign:
    if use_example:
        return example_design(game_map)
    if design_path is None:
        raise MapDesignError("give either --design or --example")
    return load_platformer_chunk_map_design_bytes(design_path.read_bytes())


def expand(
    design: PlatformerChunkMapDesign, profile: PlatformerProfile
) -> tuple[DesignedMap, list[str]]:
    """Re-expand a sentence and return the map plus every problem, in chunk vocabulary."""

    if design.columns != profile.geometry.columns:
        raise MapDesignError(
            f"design declares {design.columns} columns and the map is "
            f"{profile.geometry.columns} wide; a design may not resize the grid"
        )
    payload: dict[str, object] = {
        "design_notes": design.design_notes,
        "start_height_tiles": design.start_height_tiles,
        "chunks": list(design.chunks),
    }
    designed, errors, spans = expand_chunks(payload, profile, profile.geometry.columns)
    return designed, errors + translate(check(designed, profile), spans)


def describe(designed: DesignedMap, profile: PlatformerProfile) -> str:
    surfaces = designed.surfaces(profile)
    platforms = [entry for entry in surfaces if not entry.grounded]
    depths = [designed.ground_depth(column, profile) for column in range(designed.columns)]
    heights = sorted({entry.height_tiles for entry in platforms})
    return (
        f"{profile.profile_id}: {designed.rows} rows x {designed.columns} columns\n"
        f"  ground {min(depths)}-{max(depths)} tiles\n"
        f"  {len(platforms)} floating platform(s) at heights {heights}\n"
        f"  {len(designed.climbables)} climbable(s) at columns "
        f"{[entry.foot_column for entry in designed.climbables]}\n"
        f"  vocabulary: {', '.join(vocabulary(profile))}"
    )


def listed(headline: str, problems: Sequence[str]) -> str:
    return headline + "".join(f"\n  - {problem}" for problem in problems)


def render(designed: DesignedMap, profile: PlatformerProfile, out: Path, title: str) -> None:
    """Write a diagnostic PNG. This is a working picture, not a publishable figure."""

    from PIL import Image, ImageDraw

    if out.resolve().is_relative_to((REPOSITORY_ROOT / "docs").resolve()):
        raise MapDesignError("refusing to write a diagnostic render into docs/")
    cell, pad, label = 6, 12, 22
    width = designed.columns * cell + pad * 2
    height = designed.rows * cell + label + pad
    image = Image.new("RGB", (width, height), (250, 248, 244))
    draw = ImageDraw.Draw(image)
    draw.text((pad, 6), title, fill=(20, 20, 20))
    empty = profile.empty_role.symbol
    ground = profile.ground_role.symbol
    for tile_height in range(1, designed.rows + 1):
        for column in range(designed.columns):
            symbol = designed.symbol_at(column, tile_height)
            if symbol == empty:
                continue
            colour = (122, 96, 66) if symbol == ground else (214, 158, 62)
            top = label + (designed.rows - tile_height) * cell
            left = pad + column * cell
            draw.rectangle([left, top, left + cell - 1, top + cell - 1], fill=colour)
    for climbable in designed.climbables:
        foot = climbable.foot_height_tiles or 0
        top = label + (designed.rows - foot - climbable.rise_tiles) * cell
        left = pad + climbable.foot_column * cell
        draw.rectangle(
            [left + 1, top, left + cell - 2, label + (designed.rows - foot) * cell - 1],
            fill=(198, 60, 52),
        )
    out.parent.mkdir(parents=True, exist_ok=True)
    image.save(out)


def run_check(args: argparse.Namespace) -> int:
    game_map = load_map(args.library_root, args.map_id)
    profile = terrain_profile(game_map)
    designed, problems = expand(resolve_design(game_map, args.design, args.example), profile)
    print(describe(designed, profile))
    if problems:
        print()
        print(listed("REJECTED:", problems))
        return 1
    print(f"\ndesign satisfies every rule {args.map_id} declares")
    return 0


def run_render(args: argparse.Namespace) -> int:
    game_map = load_map(args.library_root, args.map_id)
    profile = terrain_profile(game_map)
    designed, problems = expand(resolve_design(game_map, args.design, args.example), profile)
    render(designed, profile, args.out, f"{args.map_id} - {'PASS' if not problems else 'FAIL'}")
    print(describe(designed, profile))
    if problems:
        print()
        print(listed("REJECTED:", problems))
    print(f"\nrendered: {args.out}")
    return 1 if problems else 0


def run_compile(args: argparse.Namespace) -> int:
    """Expand a design into the terrain artifact a run consumes.

    This writes an artifact into a run directory. It never touches the authored library.
    """

    game_map = load_map(args.library_root, args.map_id)
    profile = terrain_profile(game_map)
    designed, problems = expand(resolve_design(game_map, args.design, args.example), profile)
    if problems:
        print(listed("REJECTED:", problems))
        return 1
    terrain = compile_terrain(designed, game_map)
    validate_generated_terrain(game_map, terrain)
    out = args.run_dir / terrain_artifact_path(args.map_id)
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_bytes(canonical_prepared_map_terrain_json(terrain))
    print(describe(designed, profile))
    print(f"\nwrote {out}")
    return 0


async def _compose(args: argparse.Namespace, game_map: PreparedGameMap) -> int:
    from stage_gen.config import load_config
    from stage_gen.orchestration.runtime import create_structured_service

    config = load_config()
    service = create_structured_service(
        api_key=config.open_router_api_key or "",
        model=config.text_model,
        base_url=config.open_router_base_url or "https://openrouter.ai/api/v1",
    )
    profile = terrain_profile(game_map)
    try:
        attempts = await design_chunks(
            service,
            profile,
            DesignBrief(intent=game_map.terrain.brief),
            artifact_dir=args.out.parent / f"{args.map_id}-design",
        )
    finally:
        await service.aclose()
    final = attempts[-1]
    if final.problems or final.designed is None:
        print(listed(f"REJECTED after {len(attempts)} attempt(s):", final.problems))
        return 1
    print(describe(final.designed, profile))
    print(f"\ncomposed in {len(attempts)} attempt(s); wrote {args.out}")
    return 0


def run_design(args: argparse.Namespace) -> int:
    if not args.live or os.environ.get("STAGE_GEN_RUN_LIVE") != "1":
        print(
            "composing terrain calls a provider. Re-run with --live and STAGE_GEN_RUN_LIVE=1 "
            "when that is intended."
        )
        return 1
    return asyncio.run(_compose(args, load_map(args.library_root, args.map_id)))


def _add_common(parser: argparse.ArgumentParser) -> None:
    parser.add_argument("--map", dest="map_id", required=True)
    parser.add_argument("--library-root", type=Path, default=DEFAULT_LIBRARY_ROOT)


def _add_source(parser: argparse.ArgumentParser) -> None:
    group = parser.add_mutually_exclusive_group(required=True)
    group.add_argument("--design", type=Path)
    group.add_argument("--example", action="store_true")


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(description=__doc__)
    subparsers = parser.add_subparsers(dest="command", required=True)

    checker = subparsers.add_parser("check", help="offline: validate a design against its map")
    _add_common(checker)
    _add_source(checker)
    checker.set_defaults(handler=run_check)

    renderer = subparsers.add_parser("render", help="offline: write a diagnostic PNG")
    _add_common(renderer)
    _add_source(renderer)
    renderer.add_argument("--out", type=Path, required=True)
    renderer.set_defaults(handler=run_render)

    compiler = subparsers.add_parser(
        "compile", help="offline: write the terrain artifact for a run"
    )
    _add_common(compiler)
    _add_source(compiler)
    compiler.add_argument("--run-dir", type=Path, required=True)
    compiler.set_defaults(handler=run_compile)

    designer = subparsers.add_parser("design", help="LIVE: compose a design from the map's brief")
    _add_common(designer)
    designer.add_argument("--out", type=Path, required=True)
    designer.add_argument("--live", action="store_true")
    designer.set_defaults(handler=run_design)
    return parser


def main(argv: list[str] | None = None) -> int:
    args = build_parser().parse_args(argv)
    try:
        handler = args.handler
        result = handler(args)
    except MapDesignError as error:
        print(str(error))
        return 1
    return int(result)


if __name__ == "__main__":
    raise SystemExit(main())
