#!/usr/bin/env python3
"""Check or rewrite ``docs/contract-identities.md`` from the identity table.

The table in :mod:`stage_gen.identities` reads every persisted identity from the code that
owns it. This renders it as the document the other docs may cite from, so a version string
has one authority and the prose derives (contract rule C-R5).
``tests/contract/test_contract_identities.py`` asserts the document matches.

    uv run python scripts/write_contract_identities.py            # check, non-zero if stale
    uv run python scripts/write_contract_identities.py --write    # rewrite the document
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

if __package__ in {None, ""}:
    sys.path.insert(0, str(Path(__file__).resolve().parents[1] / "src"))

from stage_gen.identities import (
    RETIRED_FAMILIES,
    RETIRED_STRINGS,
    ROLE_MEANING,
    accepted_legacy_graph_identities,
    contract_identities,
    current_versions,
)

REPOSITORY_ROOT = Path(__file__).resolve().parents[1]
DOCUMENT = REPOSITORY_ROOT / "docs/contract-identities.md"


def render() -> str:
    lines = [
        "# Contract identities",
        "",
        "<!-- Generated by `uv run python scripts/write_contract_identities.py --write`. -->",
        "<!-- Do not edit by hand: the test refuses a document that differs from the code. -->",
        "",
        "Every persisted identity string the repository currently publishes, plus graph",
        "identities its readers still accept for historical compatibility, read from the",
        "one place in the code that declares each identity. This is the document the other",
        "documents cite from: a current artifact may publish an identity only at the",
        "version listed in the current table, and may not publish a retired family at all",
        "(`docs/game-contract.md`, versioning rule C-R5). A node's `contract_version` is",
        "not an identity but a cache key (C-R1); its evidence is the cache-key goldens.",
        "",
        "## Roles",
        "",
        "| Role | Meaning |",
        "| --- | --- |",
    ]
    lines.extend(f"| `{role}` | {meaning} |" for role, meaning in ROLE_MEANING.items())
    lines += [
        "",
        "## Current identities",
        "",
        "| Identity | Role | Authority |",
        "| --- | --- | --- |",
    ]
    for current_entry in sorted(contract_identities(), key=lambda item: (item.role, item.identity)):
        lines.append(
            f"| `{current_entry.identity}` | `{current_entry.role}` | `{current_entry.source}` |"
        )
    lines += [
        "",
        "## Accepted legacy graph identities",
        "",
        "These identity pairs remain readable only for route-free historical graph",
        "documents. New plans never publish them. They are neither current identities nor",
        "retired while their owning reader explicitly declares this compatibility.",
        "",
        "| Identity | Schema version | Authority |",
        "| --- | ---: | --- |",
    ]
    for legacy_entry in sorted(accepted_legacy_graph_identities(), key=lambda item: item.identity):
        lines.append(
            f"| `{legacy_entry.identity}` | `{legacy_entry.schema_version}` | "
            f"`{legacy_entry.source.legacy_authority}` |"
        )
    doubled = {family: sorted(v) for family, v in current_versions().items() if len(v) > 1}
    lines += [
        "",
        "## Retired identities",
        "",
        "Every `<family>-v<n>` whose family appears above with `n` below the listed version is",
        "retired unless it appears in the accepted-legacy table. Current artifacts may",
        "publish none of them. Where one family name carries two live versions, both are current: "
        + ", ".join(
            f"`{family}` at " + " and ".join(f"v{v}" for v in versions)
            for family, versions in sorted(doubled.items())
        )
        + ".",
        "",
        "These families have no current member; the whole family is retired:",
        "",
        "| Family | Why |",
        "| --- | --- |",
    ]
    lines.extend(f"| `{family}` | {reason} |" for family, reason in RETIRED_FAMILIES)
    lines += [
        "",
        "And these strings, which are not version-shaped:",
        "",
        "| String | Why |",
        "| --- | --- |",
    ]
    lines.extend(f"| `{text}` | {reason} |" for text, reason in RETIRED_STRINGS)
    lines.append("")
    return "\n".join(lines)


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--write", action="store_true", help="rewrite the document")
    args = parser.parse_args()
    rendered = render()
    if args.write:
        DOCUMENT.write_text(rendered, encoding="utf-8")
        print(f"wrote {DOCUMENT.relative_to(REPOSITORY_ROOT)}")
        return 0
    if not DOCUMENT.exists() or DOCUMENT.read_text(encoding="utf-8") != rendered:
        print(f"{DOCUMENT.relative_to(REPOSITORY_ROOT)} is stale; run with --write")
        return 1
    print(f"{DOCUMENT.relative_to(REPOSITORY_ROOT)} is current")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
