"""Painted terrain: authored occupancy, painted, and masked back to a bounded band of it.

A second terrain discipline beside the 47-mask tile atlas, homed at the taxonomy path the
asset taxonomy reserved for it. Occupancy stays the sole collision authority -- nothing
here or downstream ever samples the image to decide what is solid -- and the drawn edge is
allowed to leave the authored one by a published, asymmetric tolerance, which is what
separates a painted rock mass from a rock-textured grid.
"""

from stage_gen.components.painted_terrain.canonicalize import (
    PAINTED_TERRAIN_CANONICALIZER_ID,
    PAINTED_TERRAIN_VALIDATION_ID,
    canonicalize_painted_terrain_segment,
    occupancy_window,
    painted_terrain_segment_band,
    stitch_painted_terrain,
    validate_painted_terrain_canonical,
)
from stage_gen.components.painted_terrain.guide import (
    PAINTED_TERRAIN_GUIDE_ID,
    PAINTED_TERRAIN_MODE,
    CellExposure,
    build_painted_terrain_guide,
    cell_exposure,
    painted_terrain_guide_layout,
    painted_terrain_material_identity,
    painted_terrain_occupancy_sha256,
    validate_painted_terrain_material_references,
)
from stage_gen.components.painted_terrain.models import (
    PaintedSilhouetteTolerance,
    PaintedTerrainGround,
    painted_silhouette_tolerance,
)
from stage_gen.components.painted_terrain.nodes import (
    PAINTED_TERRAIN_CANONICALIZE,
    PAINTED_TERRAIN_COMPOSE,
    PAINTED_TERRAIN_GENERATE,
    PAINTED_TERRAIN_GROUND_VALIDATION_KIND,
    PAINTED_TERRAIN_GUIDE,
    PAINTED_TERRAIN_GUIDE_KIND,
    PAINTED_TERRAIN_GUIDE_REPORT_KIND,
    PAINTED_TERRAIN_KIND,
    PAINTED_TERRAIN_NODE_TYPES,
    PAINTED_TERRAIN_PLATE_ID,
    PAINTED_TERRAIN_PLATE_KIND,
    PAINTED_TERRAIN_RAW_KIND,
    PAINTED_TERRAIN_SEGMENT_TEMPLATE,
    PAINTED_TERRAIN_VALIDATION_KIND,
    PaintedMaterial,
    PaintedTerrainHandlers,
    PaintedTerrainHost,
    PaintedTerrainLayout,
    PaintedTerrainNodeTypes,
    add_painted_terrain_nodes,
    painted_terrain_node_types,
)
from stage_gen.components.painted_terrain.prompt import painted_terrain_generation_prompt
from stage_gen.components.painted_terrain.segments import (
    PAINTED_TERRAIN_CELL_PX,
    PAINTED_TERRAIN_CONTEXT_COLUMNS,
    PAINTED_TERRAIN_GUIDE_HEIGHT,
    PAINTED_TERRAIN_GUIDE_MARGIN_PX,
    PAINTED_TERRAIN_GUIDE_WIDTH,
    PAINTED_TERRAIN_MAX_ROWS,
    PAINTED_TERRAIN_MAX_SEGMENT_COLUMNS,
    PAINTED_TERRAIN_MIN_SEGMENT_COLUMNS,
    PaintedTerrainSegment,
    painted_terrain_row_window,
    painted_terrain_segments,
)
from stage_gen.components.painted_terrain.silhouette import (
    PAINTED_TERRAIN_DILATE_PX,
    PAINTED_TERRAIN_ERODE_PX,
    PAINTED_TERRAIN_SURFACE_DILATE_PX,
    PaintedSilhouetteBand,
    painted_silhouette_band,
    painted_silhouette_report,
)
from stage_gen.components.painted_terrain.validate import (
    PAINTED_TERRAIN_SOURCE_ID,
    painted_terrain_join_discontinuity,
    validate_painted_terrain_source,
)

__all__ = [
    "PAINTED_TERRAIN_CANONICALIZE",
    "PAINTED_TERRAIN_CANONICALIZER_ID",
    "PAINTED_TERRAIN_CELL_PX",
    "PAINTED_TERRAIN_COMPOSE",
    "PAINTED_TERRAIN_CONTEXT_COLUMNS",
    "PAINTED_TERRAIN_DILATE_PX",
    "PAINTED_TERRAIN_ERODE_PX",
    "PAINTED_TERRAIN_GENERATE",
    "PAINTED_TERRAIN_GROUND_VALIDATION_KIND",
    "PAINTED_TERRAIN_GUIDE",
    "PAINTED_TERRAIN_GUIDE_HEIGHT",
    "PAINTED_TERRAIN_GUIDE_ID",
    "PAINTED_TERRAIN_GUIDE_MARGIN_PX",
    "PAINTED_TERRAIN_GUIDE_KIND",
    "PAINTED_TERRAIN_GUIDE_REPORT_KIND",
    "PAINTED_TERRAIN_GUIDE_WIDTH",
    "PAINTED_TERRAIN_KIND",
    "PAINTED_TERRAIN_MAX_ROWS",
    "PAINTED_TERRAIN_MAX_SEGMENT_COLUMNS",
    "PAINTED_TERRAIN_MIN_SEGMENT_COLUMNS",
    "PAINTED_TERRAIN_MODE",
    "PAINTED_TERRAIN_NODE_TYPES",
    "PAINTED_TERRAIN_PLATE_ID",
    "PAINTED_TERRAIN_PLATE_KIND",
    "PAINTED_TERRAIN_RAW_KIND",
    "PAINTED_TERRAIN_SEGMENT_TEMPLATE",
    "PAINTED_TERRAIN_SOURCE_ID",
    "PAINTED_TERRAIN_SURFACE_DILATE_PX",
    "PAINTED_TERRAIN_VALIDATION_ID",
    "PAINTED_TERRAIN_VALIDATION_KIND",
    "CellExposure",
    "PaintedMaterial",
    "PaintedSilhouetteBand",
    "PaintedSilhouetteTolerance",
    "PaintedTerrainGround",
    "PaintedTerrainHandlers",
    "PaintedTerrainHost",
    "PaintedTerrainLayout",
    "PaintedTerrainNodeTypes",
    "PaintedTerrainSegment",
    "add_painted_terrain_nodes",
    "build_painted_terrain_guide",
    "canonicalize_painted_terrain_segment",
    "cell_exposure",
    "occupancy_window",
    "painted_silhouette_band",
    "painted_silhouette_report",
    "painted_silhouette_tolerance",
    "painted_terrain_generation_prompt",
    "painted_terrain_guide_layout",
    "painted_terrain_join_discontinuity",
    "painted_terrain_material_identity",
    "painted_terrain_node_types",
    "painted_terrain_occupancy_sha256",
    "painted_terrain_row_window",
    "painted_terrain_segment_band",
    "painted_terrain_segments",
    "stitch_painted_terrain",
    "validate_painted_terrain_canonical",
    "validate_painted_terrain_material_references",
    "validate_painted_terrain_source",
]
