"""Standalone parser, compiler and admission for the supported v2 narrative subset.

The caller supplies narrative declarations. Game package readers and generation
metadata are intentionally outside this distribution.
"""

from .admission import (
    MAX_IMPORTED_FLAGS,
    MAX_REACHABLE_STATES,
    ScenarioAdmissionError,
    ScenarioState,
    admit_scenario,
)
from .compile import ScenarioCompileError, compile_scenario
from .models import (
    RESERVED_WORDS,
    SLOTS,
    TERMINAL_KINDS,
    AudioStatement,
    Block,
    BranchEdge,
    BranchStatement,
    CastMember,
    ChoiceOption,
    ChoiceStatement,
    Condition,
    EndingDeclaration,
    EndingWitness,
    EndStatement,
    FlagDeclaration,
    HideStatement,
    JumpStatement,
    LineStatement,
    ScenarioAdmissionReport,
    ScenarioDeclarations,
    ScenarioProgram,
    SetStatement,
    ShowStatement,
    Slot,
    StageDeclaration,
    StageStatement,
    Statement,
    TrackDeclaration,
)
from .parser import RawBlock, RawIf, ScenarioSyntaxError, parse_scenario

__all__ = [
    "RESERVED_WORDS",
    "SLOTS",
    "TERMINAL_KINDS",
    "LineStatement",
    "ShowStatement",
    "HideStatement",
    "StageStatement",
    "AudioStatement",
    "SetStatement",
    "Condition",
    "ChoiceOption",
    "ChoiceStatement",
    "BranchEdge",
    "BranchStatement",
    "JumpStatement",
    "EndStatement",
    "Block",
    "CastMember",
    "FlagDeclaration",
    "EndingDeclaration",
    "EndingWitness",
    "ScenarioAdmissionReport",
    "Slot",
    "Statement",
    "StageDeclaration",
    "TrackDeclaration",
    "ScenarioDeclarations",
    "ScenarioProgram",
    "MAX_IMPORTED_FLAGS",
    "MAX_REACHABLE_STATES",
    "ScenarioAdmissionError",
    "ScenarioState",
    "admit_scenario",
    "ScenarioCompileError",
    "compile_scenario",
    "RawBlock",
    "RawIf",
    "ScenarioSyntaxError",
    "parse_scenario",
]
